pool:
  name: "docker-ubuntu-pool"
resources:
  repositories: 
    - repository: templates 
      type: github
      name: phamsang1301/cloud_devops_2
      endpoint: github.com_phamsang1301
      ref: main
trigger:
- main
variables:
  # Set the Python version to be used
  pythonVersion: '3.10'
jobs:
- job: build
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/starter_files/flask-sklearn/flask_app.zip'
        replaceExistingArchive: true
      displayName: 'Archive Flask App'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/starter_files/flask-sklearn/flask_app.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Build Artifacts'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'studen'
        appType: 'webApp'
        appName: 'udacity'
        package: '$(Build.ArtifactStagingDirectory)/starter_files/flask-sklearn/flask_app.zip'
      displayName: 'Deploy to Azure Web App'